# Generated by Django 5.2.8 on 2025-12-02 01:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelf_number', models.IntegerField()),
                ('bay_code', models.CharField(max_length=5)),
                ('section_number', models.IntegerField()),
                ('full_location_code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'physical_location',
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_code', models.CharField(max_length=20, unique=True)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('lecturer_name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('exam_type', models.CharField(blank=True, choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz')], max_length=30, null=True)),
                ('document_type', models.CharField(choices=[('Exam', 'Exam'), ('Internship Report', 'Internship Report'), ('Grad Project', 'Graduation Project')], max_length=30)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Archived', 'Archived')], default='Available', max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('physical_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.physicallocation')),
            ],
            options={
                'db_table': 'archive_record',
            },
        ),
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archiverecord')),
            ],
            options={
                'db_table': 'borrow_transaction',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Login', 'Login'), ('Logout', 'Logout'), ('Borrow', 'Borrow'), ('Return', 'Return')], max_length=30)),
                ('table_affected', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
