# Generated by Django 5.2.8 on 2025-12-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_physicallocation_archiverecord_borrowtransaction_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='cloud_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='cloud_file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='has_digital_copy',
            field=models.BooleanField(default=False),
        ),
    ]
